name: Deploy to S3

on:
  push:
    branches: [ "develop" ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Deploy
      env:
        AWS_DEFAULT_REGION: "ap-northeast-1"
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        if [ -z "$AWS_S3_BUCKET" ]; then
          echo "AWS_S3_BUCKET is not set. Quitting."
          exit 1
        fi
        
        if [ -z "$AWS_ACCESS_KEY_ID" ]; then
          echo "AWS_ACCESS_KEY_ID is not set. Quitting."
          exit 1
        fi
        
        if [ -z "$AWS_SECRET_ACCESS_KEY" ]; then
          echo "AWS_SECRET_ACCESS_KEY is not set. Quitting."
          exit 1
        fi
        
        if [ -z "$AWS_DEFAULT_REGION" ]; then
          echo "AWS_DEFAULT_REGION is not set. Quitting."
          exit 1
        fi
        
        mkdir -p ~/.aws
        touch ~/.aws/credentials
        
        echo "[default]
        aws_access_key_id = ${AWS_ACCESS_KEY_ID}
        aws_secret_access_key = ${AWS_SECRET_ACCESS_KEY}" > ~/.aws/credentials
        
        
        echo "Install yarn"
        npm install -g yarn
        
        echo "Install dependencies"
        yarn install
        
        echo "Run yarn build"
        yarn run build
        
        echo "Copying to website folder"
        aws s3 sync ./build s3://${AWS_S3_BUCKET} --exact-timestamps --delete --region ${AWS_DEFAULT_REGION} $*
        
        echo "Cleaning up things"
        
        rm -rf ~/.aws
