name: Deploy to S3

on:
  push:
    branches: [ "develop" ]
  workflow_dispatch:

jobs:

  build:
    environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'development' }}
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: 'npm'
    - run: npm install
    - name: create env file
      run: |
        touch .env
        echo TYPESENSE_COLLECTION_NAME=${{ vars.TYPESENSE_COLLECTION_NAME }} >> .env
        echo TYPESENSE_SERVER_HOST=${{ vars.TYPESENSE_SERVER_HOST }} >> .env
        echo TYPESENSE_SEARCH_ONLY_APIKEY=${{ vars.TYPESENSE_SEARCH_ONLY_APIKEY }} >> .env
    - run: npm run build
    - name: Deploy
      env:
        AWS_DEFAULT_REGION: "ap-northeast-1"
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        if [ -z "$AWS_S3_BUCKET" ]; then
          echo "AWS_S3_BUCKET is not set. Quitting."
          exit 1
        fi
        
        if [ -z "$AWS_ACCESS_KEY_ID" ]; then
          echo "AWS_ACCESS_KEY_ID is not set. Quitting."
          exit 1
        fi
        
        if [ -z "$AWS_SECRET_ACCESS_KEY" ]; then
          echo "AWS_SECRET_ACCESS_KEY is not set. Quitting."
          exit 1
        fi
        
        if [ -z "$AWS_DEFAULT_REGION" ]; then
          echo "AWS_DEFAULT_REGION is not set. Quitting."
          exit 1
        fi
        
        mkdir -p ~/.aws
        touch ~/.aws/credentials
        
        echo "[default]
        aws_access_key_id = ${AWS_ACCESS_KEY_ID}
        aws_secret_access_key = ${AWS_SECRET_ACCESS_KEY}" > ~/.aws/credentials
        
        echo "Copying to website folder"
        aws s3 sync ./build s3://${AWS_S3_BUCKET} --exact-timestamps --delete --region ${AWS_DEFAULT_REGION} $*
        
        echo "Cleaning up things"
        
        rm -rf ~/.aws
