name: Update Typesense

on:
  workflow_dispatch:
  push:
    branches: [develop]

jobs:
  build:
    name: Update Typesense index
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - run: |
          docker run -e TYPESENSE_API_KEY="${{ secrets.TYPESENSE_API_KEY }}" \
            -e TYPESENSE_HOST="typesense.test.aelf.dev" \
            -e TYPESENSE_PORT=443 \
            -e TYPESENSE_PROTOCOL=https \
            -e "CONFIG=$(cat config/typesense.json | jq -r tostring)" typesense/docsearch-scraper:0.9.1