name: Update Typesense

on:
  workflow_dispatch:
  push:
    branches: [develop]

jobs:
  build:
    name: Update Typesense index
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Run DocSearch Scraper
        uses: celsiusnarhwal/typesense-scraper@v2
        with:
          # The secret containing your Typesense API key. Required.
          api-key: ${{ secrets.TYPESENSE_API_KEY }}
          
          # The hostname or IP address of your Typesense server. Required.
          host: ${{ secrets.TYPESENSE_HOST }}
          
          # The port on which your Typesense server is listening. Optional. Default: 8108.
          port: 443
          
          # The protocol to use when connecting to your Typesense server. Optional. Default: http.
          protocol: https
          
          # The path to your DocSearch config file. Optional. Default: docsearch.config.json.
          config: config/typesense.json